on:
  schedule:
  - cron: "5 * * * *"

name: update-data

jobs:
  update-data:
    runs-on: ${{ matrix.config.os }}

    strategy:
      fail-fast: false
      matrix:
        config:
          - {os: windows-latest, r: '3.6'}
          - {os: macOS-latest, r: '3.6'}
          - {os: macOS-latest, r: 'devel'}
          - {os: ubuntu-16.04, r: '3.6', cran: "https://demo.rstudiopm.com/all/__linux__/xenial/latest"}

    env:
      R_REMOTES_NO_ERRORS_FROM_WARNINGS: true
      CRAN: ${{ matrix.config.cran }}

    steps:
      - uses: actions/checkout@v1
      - uses: r-lib/actions/setup-r@master
        with:
          r-version: ${{ matrix.config.r }}
      - uses: r-lib/actions/setup-pandoc@v1
      - name: Install more packages
        run: Rscript -e 'install.packages(c("rmarkdown", "DBI", "RMySQL", "devtools", "pins", "dplyr","safer"))'
      - name: Install package for ip address if need to allow a new one
        run: Rscript -e 'devtools::install_git("https://gitlab.com/hrbrmstr/myip")' -e 'devtools::install_github("r-dbi/RMySQL")'
      - name: Add credentials
        run: Rscript -e 'myGithubToken <- "${{secrets.PREDICTCRYPTO_PINS}}"' -e 'ip_secrets <- "${{secrets.IP}}"' -e 'pswd_secrets <- "${{secrets.PSWD}}"' -e 'rmarkdown::render("pull_data.Rmd")'
