on: [push, pull_request]

name: update-data

jobs:
  update-data:
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v1
      - uses: r-lib/actions/setup-pandoc@v1
      - uses: r-lib/actions/setup-r@master
      - name: Install dependencies
        run: Rscript -e "install.packages(c('remotes', 'rcmdcheck'))" -e "remotes::install_deps(dependencies = TRUE)"
      - name: Install more packages
        run: Rscript -e 'install.packages(c("rmarkdown", "DBI", "RMySQL", "devtools", "pins", "dplyr"))'
      - name: Install package for ip address if need to allow a new one
        run: Rscript -e 'devtools::install_git("https://gitlab.com/hrbrmstr/myip")'
      - name: Refresh datasets
        run: Rscript -e 'myGithubToken <- "${{secrets.GITHUB_PAT_PINS3}}"' -e 'rmarkdown::render("PullData.Rmd")'
