on:
  schedule:
  - cron: "0 * * * *"

name: update-data

jobs:
  update-data:
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v1
      - uses: r-lib/actions/setup-pandoc@v1
      - uses: r-lib/actions/setup-r@master
      - name: Install more packages
        run: Rscript -e 'install.packages(c("rmarkdown", "DBI", "RMySQL", "devtools", "pins", "dplyr","safer"))'
      - name: Install package for ip address if need to allow a new one
        run: Rscript -e 'devtools::install_git("https://gitlab.com/hrbrmstr/myip")' -e 'devtools::install_github("r-dbi/RMySQL")'
      - name: Add credentials
        run: Rscript -e 'myGithubToken <- "${{secrets.GITHUB_PAT_PINS3}}"' -e 'git_key <- "${{secrets.GITHUB_KEY}}"'
      - name: Refresh datasets
        run: Rscript -e 'install.packages("RMySQL")' -e 'rmarkdown::render("PullData.Rmd")'
