on: [push, pull_request]

name: update-data
  schedule:
  - cron: "0 0 * * *"

jobs:
  update-data:
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v1
      - uses: r-lib/actions/setup-pandoc@v1
      - uses: r-lib/actions/setup-r@master
      - name: Install dependencies
        run: Rscript -e "install.packages(c('remotes', 'rcmdcheck'))" -e "remotes::install_deps(dependencies = TRUE)"
      - name: Install more packages
        run: Rscript -e 'install.packages(c("rmarkdown", "DBI", "RMySQL"))'
      - name: Refresh datasets
        run: Rscript -e 'rmarkdown::render("PullData.Rmd")'
